const SET_IS_FETCHING_CATEGORIES = "SET_IS_FETCHING_CATEGORIES";
const SET_IS_POSTING_CATEGORY = "SET_IS_POSTING_CATEGORY";
const GET_CATEGORIES = 'GET_CATEGORIES'
const ADD_CATEGORY = "ADD_CATEGORY";
const EDIT_CATEGORY = "EDIT_CATEGORY";
const DELETE_CATEGORY = "DELETE_CATEGORY";
const SET_IS_FETCHING_PRODUCTS = "SET_IS_FETCHING_CATEGORIES";
const SET_IS_POSTING_PRODUCT = "SET_IS_POSTING_PRODUCT";
const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
const ADD_PRODUCT = "ADD_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT"
const LOGIN_ADMIN = "LOGIN_ADMIN";
const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export {
    SET_IS_FETCHING_CATEGORIES,
    SET_IS_POSTING_CATEGORY,
    GET_CATEGORIES,
    ADD_CATEGORY,
    EDIT_CATEGORY,
    DELETE_CATEGORY,
    SET_IS_FETCHING_PRODUCTS,
    SET_IS_POSTING_PRODUCT,
    GET_PRODUCTS_BY_CATEGORY,
    ADD_PRODUCT,
    EDIT_PRODUCT,
    DELETE_PRODUCT,
    LOGIN_ADMIN,
    LOGOUT_ADMIN
}