const GET_CATEGORIES = 'GET_CATEGORIES'
const ADD_CATEGORY = "ADD_CATEGORY";
const EDIT_CATEGORY = "EDIT_CATEGORY";
const DELETE_CATEGORY = "DELETE_CATEGORY";
const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
const ADD_PRODUCT = "ADD_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT"
const LOGIN_ADMIN = "LOGIN_ADMIN";

export {
    GET_CATEGORIES,
    ADD_CATEGORY,
    EDIT_CATEGORY,
    DELETE_CATEGORY,
    GET_PRODUCTS_BY_CATEGORY,
    ADD_PRODUCT,
    EDIT_PRODUCT,
    DELETE_PRODUCT,
    LOGIN_ADMIN
}